### ISSUE TITLE
How to implement Bidirectional LSTM

### ISSUE THREAD

**Issue by futurely** [Russell91/LSTMSummation#3]
After training with `python train.py --gpu -1 --config config.json`, I got much smaller residuals compared with the results in the `README.md`. The larger residuals appeared near the begining and the end of the sequence possibly due to lack of enough context as the elements around the middle of the sequence. Bidirectional LSTM (BLSTM) may be able to overcome this problem. Can BLSTM be implemented with ApolloCaffe? If the answer is yes, then how to do it?
```
The target values were:
0.50,	1.00,	1.50,	2.00,	2.50,	3.00,	3.50,	4.00,	4.50,	5.00,	5.50,	6.00,	6.50,	7.00,	7.50,	8.00,	8.50,	9.00,	9.50,	10.00

The network predicted:
0.72,	1.15,	1.59,	2.04,	2.51,	2.99,	3.48,	3.99,	4.50,	5.01,	5.53,	6.04,	6.55,	7.05,	7.54,	8.01,	8.48,	8.94,	9.38,	9.81

The residuals are:
0.22,	0.15,	0.09,	0.04,	0.01,	-0.01,	-0.02,	-0.01,	-0.00,	0.01,	0.03,	0.04,	0.05,	0.05,	0.04,	0.01,	-0.02,	-0.06,-0.12,	-0.19
```

**Comment by Russell91** [comment]
If you set up two distinct LSTM chains, and then use concat layers on the hidden states of each chain, you would end up with a bidirectional LSTM.

**Comment by futurely** [comment]
tensorflow/python/ops/rnn.py added bidirectional_rnn two days ago. https://github.com/tensorflow/tensorflow/commit/e4556746cea3fc8123ce44c4db0ebff76053ae52
