### ISSUE TITLE
questions for the lstm_unit_layer.cpp

### ISSUE THREAD

**Issue by chenfsjz** [Russell91/LSTMSummation#4]
I just study your code of LSTM's implemantation. In the backward_cpu, I can understand how to compute the term of "prev_state_diff", but in the following steps, you have computed the term  "input_diff" for four times after each **weight_diff. And I don't understand why you compute the four times. Can you give me some explaination! Thank you.

**Comment by Russell91** [comment]
Each of the gates propagates signal back to the input (read: hidden) diff. The four calls add in the component from the input, forget, output, and input_value gates, respectively. Does that make sense?

**Comment by chenfsjz** [comment]
yes, I see, thank you.
(1)In the forward, the term "next_hidden_state[idx] = next_memory_state[idx] * output_gates[idx]", does it means that you does't use the formula: h(t) = o(t)*f(c(t)), and its a commen formula in many papers.
(2)as the this term show, they are the last input_diff 's  computation. why don't you take the "next_memory_state_diff" to compute the dldg_data.
caffe_mul(num_ * channels_, output_gates_diff, next_memory_state, dldg_data);
caffe_mul(num_ * channels_, next_hidden_state_diff, dldg_data, dldg_data);

**Comment by Russell91** [comment]
(1) Yea, that's correct. There is a more recent version on the dev branch that allows you to use tanh_hidden units. I and others around me have found no tanh does every bit as well, but conforming is good so it's now provided as an option.

(2) Not sure how to answer this. But the gradient checks pass, which is the ultimate justification :).

**Comment by chenfsjz** [comment]
thank you! I'll go deeper with lstm and learn how to use it.
